name: Build and run integration tests
on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Pact tests
        working-directory: Fluke
        run: |
          dotnet test --filter "TestCategory=Pact|Integration" \
                      --logger:"console;verbosity=detailed" \
                      --logger "trx;LogFileName=test-results.trx"
 
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-pact
          path: "./Fluke.Tests.Pact/TestResults/test-results.trx"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-integration
          path: "./Fluke.Tests.Integration/TestResults/test-results.trx"
          
  prepare-test-report:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: test-report-pact
      - uses: actions/download-artifact@v4
        with:
          name: test-report-integration

      - name: Prepare Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Test Report
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
